/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MocktestRouteImport } from './routes/mocktest'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MocktestTestTestIdRouteImport } from './routes/mocktest.test.$testId'
import { Route as MocktestTestTestIdStartRouteImport } from './routes/mocktest.test.$testId.start'

const MocktestRoute = MocktestRouteImport.update({
  id: '/mocktest',
  path: '/mocktest',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MocktestTestTestIdRoute = MocktestTestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => MocktestRoute,
} as any)
const MocktestTestTestIdStartRoute = MocktestTestTestIdStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => MocktestTestTestIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mocktest': typeof MocktestRouteWithChildren
  '/mocktest/test/$testId': typeof MocktestTestTestIdRouteWithChildren
  '/mocktest/test/$testId/start': typeof MocktestTestTestIdStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mocktest': typeof MocktestRouteWithChildren
  '/mocktest/test/$testId': typeof MocktestTestTestIdRouteWithChildren
  '/mocktest/test/$testId/start': typeof MocktestTestTestIdStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mocktest': typeof MocktestRouteWithChildren
  '/mocktest/test/$testId': typeof MocktestTestTestIdRouteWithChildren
  '/mocktest/test/$testId/start': typeof MocktestTestTestIdStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/mocktest'
    | '/mocktest/test/$testId'
    | '/mocktest/test/$testId/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/mocktest'
    | '/mocktest/test/$testId'
    | '/mocktest/test/$testId/start'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/mocktest'
    | '/mocktest/test/$testId'
    | '/mocktest/test/$testId/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MocktestRoute: typeof MocktestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mocktest': {
      id: '/mocktest'
      path: '/mocktest'
      fullPath: '/mocktest'
      preLoaderRoute: typeof MocktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mocktest/test/$testId': {
      id: '/mocktest/test/$testId'
      path: '/test/$testId'
      fullPath: '/mocktest/test/$testId'
      preLoaderRoute: typeof MocktestTestTestIdRouteImport
      parentRoute: typeof MocktestRoute
    }
    '/mocktest/test/$testId/start': {
      id: '/mocktest/test/$testId/start'
      path: '/start'
      fullPath: '/mocktest/test/$testId/start'
      preLoaderRoute: typeof MocktestTestTestIdStartRouteImport
      parentRoute: typeof MocktestTestTestIdRoute
    }
  }
}

interface MocktestTestTestIdRouteChildren {
  MocktestTestTestIdStartRoute: typeof MocktestTestTestIdStartRoute
}

const MocktestTestTestIdRouteChildren: MocktestTestTestIdRouteChildren = {
  MocktestTestTestIdStartRoute: MocktestTestTestIdStartRoute,
}

const MocktestTestTestIdRouteWithChildren =
  MocktestTestTestIdRoute._addFileChildren(MocktestTestTestIdRouteChildren)

interface MocktestRouteChildren {
  MocktestTestTestIdRoute: typeof MocktestTestTestIdRouteWithChildren
}

const MocktestRouteChildren: MocktestRouteChildren = {
  MocktestTestTestIdRoute: MocktestTestTestIdRouteWithChildren,
}

const MocktestRouteWithChildren = MocktestRoute._addFileChildren(
  MocktestRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MocktestRoute: MocktestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
